name: Setup

description: Sets up PHP and Composer

inputs:
  php-version:
    description: The PHP version(s) to use
    required: true
  php-extensions:
    description: The PHP extensions you want to install
    required: false
    default: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr

runs:
  using: composite
  steps:
    - name: Get PHP extension cache hash
      id: get-cache-hash
      run: echo hash=$(echo $PHP_EXTENSIONS | md5sum | awk '{print $1}') >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        key: php-extensions-${{ steps.get-cache-hash.outputs.hash }}

    - name: Cache extensions
      uses: actions/cache@v4
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Setup PHP and Composer
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        tools: composer:v2

    - name: Get Composer cache dir
      id: composer-cache-dir
      run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v4.2.0
      with:
        key: composer-cache-${{ hashFiles('**/composer.lock') }}
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        restore-keys: composer-cache-